Data from https://lars.yencken.org/datasets/kanji-confusion
as part of
Yencken, Lars (2010) Orthographic support for passing the reading hurdle in Japanese. PhD Thesis, University of Melbourne, Melbourne, Australia
made available under a Creative Commons Attribution 3.0 Unported license

```{r}
# We depend on dendextend->ggplot2->mgcv->Matrix, so no need to install.
library(Matrix)
library(kanjistat)
```

```{r}
# A function to convert csv files from https://lars.yencken.org/datasets/kanji-confusion
csvToSparseMatrix <- function(file) {
  data <- read.csv(file, header = FALSE, stringsAsFactors = FALSE)
  
  pairSet <- new.env(hash = TRUE)  # Environment used as a hash set
  
  processRow <- function(row) {
    elements <- strsplit(row, " ")[[1]]
    rowKey <- elements[1]
    rows <- integer()
    cols <- integer()
    values <- numeric()
    
    for (i in seq(2, length(elements), by = 2)) {
        colKey <- elements[i]
        value <- 1 - as.numeric(elements[i + 1])
        if (value == 0) {
          value <- 1e-6 
          # smallest value represented explicitly (without scientific notation)
          # for the default setting of 7 in options("digits")
        }
        rowIndex <- match(rowKey, kanjistat::kbase$kanji)
        colIndex <- match(colKey, kanjistat::kbase$kanji)
        
        # Ignoring Kanji that are not jouyou anymore 
        if (max(rowIndex, colIndex) > 2136) { 
          next
        }
        
        # Ensure the lower index is always first
        if (rowIndex > colIndex) {
          temp <- rowIndex
          rowIndex <- colIndex
          colIndex <- temp
        }
        
        pairKey <- paste(rowIndex, colIndex, sep = "-")
        if (!exists(pairKey, pairSet)) {
          pairSet[[pairKey]] <- TRUE
          rows <- c(rows, rowIndex)
          cols <- c(cols, colIndex)
          
          values <- c(values, value)
        }
    }
    
    list(rows = rows, cols = cols, values = values)
  }
  
  processedData <- do.call(rbind, lapply(data$V1, processRow))
  rows <- unlist(processedData[, "rows"])
  cols <- unlist(processedData[, "cols"])
  values <- unlist(processedData[, "values"])
  
  sparseMatrix(i = rows, j = cols, x = values, symmetric = TRUE)
}

# Create the sparse matrix
# File paths relative to data-raw not project root (which is ok if present file was double-clicked)
dstrokedit <- csvToSparseMatrix("jyouyou__strokeEditDistance.csv")
dyehli <- csvToSparseMatrix("jyouyou__yehAndLiRadical.csv")
digest::digest(dstrokedit, algo="sha256") == "34381068e6e52bcef5ea76f121910556e37a51f37072b056437be1a42d58fcc7"
digest::digest(dyehli, algo="sha256") == "8f68cd9f98750b087fa091d2e9c80abe5dbbd101e4f8d7cf0dab22c26e0a8520"
#  kanjistat v0.11.0, 240216 

save(dstrokedit, file="../data/dstrokedit.rda", compress="xz")
save(dyehli, file="../data/dyehli.rda", compress="xz")   

```

```{r}
# A simple manual check of equivalence to the csv file
dmatrix <- dyehli

bu_index <- match("部", kbase$kanji)
non_zero <- which(dmatrix[bu_index,] != 0)
result <- rbind(kbase[non_zero,]$kanji, as.numeric(dmatrix[non_zero,bu_index]))
result[, order(as.numeric(result[2,]))]

ka_index <- match("佳", kbase$kanji)
non_zero <- which(dmatrix[ka_index,] != 0)
result <- rbind(kbase[non_zero,]$kanji, as.numeric(dmatrix[non_zero,ka_index]))
result[, order(as.numeric(result[2,]))]
```


















