# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cubic_bezier_point_cpp <- function(t, p0, p1, p2, p3) {
    .Call(`_kanjistat_cubic_bezier_point_cpp`, t, p0, p1, p2, p3)
}

cubic_bezier_curve_cpp <- function(t, p0, p1, p2, p3) {
    .Call(`_kanjistat_cubic_bezier_curve_cpp`, t, p0, p1, p2, p3)
}

cubic_bezier_curve_eqspaced_cpp <- function(density, n, p0, p1, p2, p3) {
    .Call(`_kanjistat_cubic_bezier_curve_eqspaced_cpp`, density, n, p0, p1, p2, p3)
}

bezier_curve_cpp <- function(beziermat, ncurves, point_density, eqspaced) {
    .Call(`_kanjistat_bezier_curve_cpp`, beziermat, ncurves, point_density, eqspaced)
}

ftestloop <- function(n) {
    .Call(`_kanjistat_ftestloop`, n)
}

itestloop <- function(n) {
    .Call(`_kanjistat_itestloop`, n)
}

idtestloop <- function(n) {
    .Call(`_kanjistat_idtestloop`, n)
}

match_diagonal_trafo <- function(points1, points2) {
    .Call(`_kanjistat_match_diagonal_trafo`, points1, points2)
}

