# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cubic_bezier_point_cpp <- function(t, p0, p1, p2, p3) {
    .Call(`_kanjistat_cubic_bezier_point_cpp`, t, p0, p1, p2, p3)
}

cubic_bezier_curve_cpp <- function(t, p0, p1, p2, p3) {
    .Call(`_kanjistat_cubic_bezier_curve_cpp`, t, p0, p1, p2, p3)
}

